In [36]:
import os 

os.getcwd()

'/home/piero/Desktop/Becode/Projects/immo_eliza_regression/challenge-regression/data'

In [37]:
import pandas as pd
import numpy as np
import os 

os.chdir('/home/piero/Desktop/Becode/Projects/immo_eliza_regression/challenge-regression/data')
df = pd.read_csv('data_model.csv')
df

,Unnamed: 0,price,area,property-type,rooms-number,zip-code,land-area,garden,garden-area,equipped-kitchen,full-address,swimming-pool,furnished,open-fire,terrace,terrace-area,facades-number,building-state
0,0,159000,122,house,2,4430,335,1,171,1.0,ans,0,0,0,1,20,2,good
1,1,345000,119,house,4,9000,49,0,0,1.0,gent,0,0,0,0,0,2,good
2,2,570000,404,house,4,1570,1000,1,1000,1.0,galmaarden,0,0,0,1,52,4,as new
3,3,800000,350,house,4,1190,263,1,140,1.0,forest,0,0,0,0,0,2,to rebuild
4,4,425000,130,house,3,4950,991,0,0,1.0,waimes,0,0,0,1,14,4,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7683,7683,327000,84,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,6,2,not mentioned
7684,7684,327250,90,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,9,2,not mentioned
7685,7685,329500,84,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,6,2,not mentioned
7686,7686,329500,80,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,18,2,not mentioned
7687,7687,329750,90,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,9,2,not mentioned

In [38]:
df = df.drop('Unnamed: 0', axis=1)

In [39]:
df.to_csv('data_model.csv', index=False)
df = pd.read_csv('data_model.csv')
df

,price,area,property-type,rooms-number,zip-code,land-area,garden,garden-area,equipped-kitchen,full-address,swimming-pool,furnished,open-fire,terrace,terrace-area,facades-number,building-state
0,159000,122,house,2,4430,335,1,171,1.0,ans,0,0,0,1,20,2,good
1,345000,119,house,4,9000,49,0,0,1.0,gent,0,0,0,0,0,2,good
2,570000,404,house,4,1570,1000,1,1000,1.0,galmaarden,0,0,0,1,52,4,as new
3,800000,350,house,4,1190,263,1,140,1.0,forest,0,0,0,0,0,2,to rebuild
4,425000,130,house,3,4950,991,0,0,1.0,waimes,0,0,0,1,14,4,good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7683,327000,84,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,6,2,not mentioned
7684,327250,90,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,9,2,not mentioned
7685,329500,84,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,6,2,not mentioned
7686,329500,80,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,18,2,not mentioned
7687,329750,90,apartment,2,8370,0,0,0,1.0,blankenberge,0,0,0,1,9,2,not mentioned

In [40]:
df.dtypes

price                 int64
area                  int64
property-type        object
rooms-number          int64
zip-code              int64
land-area             int64
garden                int64
garden-area           int64
equipped-kitchen    float64
full-address         object
swimming-pool         int64
furnished             int64
open-fire             int64
terrace               int64
terrace-area          int64
facades-number        int64
building-state       object
dtype: object

In [41]:
print(df['property-type'].unique())
print(df['building-state'].unique())

['house' 'apartment']
['good' 'as new' 'to rebuild' 'to renovate' 'just renovated'
 'not mentioned']

In [42]:
#"NEW" | "GOOD" | "TO RENOVATE" | "JUST RENOVATED" | "TO REBUILD"
df[df['state_of_the_building']=='not mentioned']

KeyError: 'state_of_the_building'